namespace Yulinti.Nucleus {
    public enum IDErrorum {
        OK = 0,

        // Rex: 1000 ~
        REX_ANCHORA_NOT_SET = 1000,
        REX_ANCHORA_RESOLVE_FAILED = 1001,

        // Nucleus: 2000 ~

        // MinisteriaUnity.Anchora: 10000~
        ANCHORACAMERA_CAMERA_NULL = 10000,

        ANCHORACIVIS_PREFAB_INSTANCE_NULL = 10010,
        ANCHORACIVIS_ANIMATOR_NULL = 10011,
        ANCHORACIVIS_SKINNEDMESHRENDERER_NULL = 10012,
        ANCHORACIVIS_CHARACTERCONTROLLER_NULL = 10013,
        ANCHORACIVIS_NAVMESHAGENT_NULL = 10014,
        ANCHORACIVIS_INSTANCE_NULL = 10015,
        ANCHORACIVIS_INFERIOR_ANCHOR_NULL = 10016,
        ANCHORACIVIS_ANIMANCER_NULL = 10017,
        
        ANCHORAINPUT_MOVEINPUT_NULL = 10020,
        ANCHORAINPUT_SPRINTINPUT_NULL = 10021,
        ANCHORAINPUT_CROUCHINPUT_NULL = 10022,

        ANCHORAPUELLAE_CHARACTERCONTROLLER_NULL = 10100,
        ANCHORAPUELLAE_ANIMATOR_NULL = 10102,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_HEAD_NULL = 10110,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_PELVIS_NULL = 10111,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_TORSO_NULL = 10112,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_RIGHTARM_NULL = 10113,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_LEFTARM_NULL = 10114,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_RIGHTLEG_NULL = 10115,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_LEFTLEG_NULL = 10116,
        ANCHORAPUELLAE_BONE_ROOT_NULL = 10130,
        ANCHORAPUELLAE_BONE_HIPS_NULL = 10131,
        ANCHORAPUELLAE_BONE_SPINE_NULL = 10132,
        ANCHORAPUELLAE_BONE_SPINE1_NULL = 10133,
        ANCHORAPUELLAE_BONE_SPINE2_NULL = 10134,
        ANCHORAPUELLAE_BONE_NECK_NULL = 10135,
        ANCHORAPUELLAE_BONE_HEAD_NULL = 10136,
        ANCHORAPUELLAE_BONE_LEFTSHOULDER_NULL = 10137,
        ANCHORAPUELLAE_BONE_LEFTUPPERARM_NULL = 10138,
        ANCHORAPUELLAE_BONE_LEFTLOWERARM_NULL = 10139,
        ANCHORAPUELLAE_BONE_LEFTHAND_NULL = 10140,
        ANCHORAPUELLAE_BONE_RIGHTSHOULDER_NULL = 10141,
        ANCHORAPUELLAE_BONE_RIGHTUPPERARM_NULL = 10142,
        ANCHORAPUELLAE_BONE_RIGHTLOWERARM_NULL = 10143,
        ANCHORAPUELLAE_BONE_RIGHTHAND_NULL = 10144,
        ANCHORAPUELLAE_BONE_LEFTUPPERLEG_NULL = 10145,
        ANCHORAPUELLAE_BONE_LEFTLOWERLEG_NULL = 10146,
        ANCHORAPUELLAE_BONE_LEFTFOOT_NULL = 10147,
        ANCHORAPUELLAE_BONE_LEFTTOE_NULL = 10148,
        ANCHORAPUELLAE_BONE_RIGHTUPPERLEG_NULL = 10149,
        ANCHORAPUELLAE_BONE_RIGHTLOWERLEG_NULL = 10150,
        ANCHORAPUELLAE_BONE_RIGHTFOOT_NULL = 10151,
        ANCHORAPUELLAE_BONE_RIGHTTOE_NULL = 10152,
        ANCHORAPUELLAE_BONE_HIPS_RIGHT_X150PIN_NULL = 10153,
        ANCHORAPUELLAE_BONE_HIPS_RIGHT_Y90PIN_NULL = 10154,
        ANCHORAPUELLAE_BONE_HIPS_LEFT_X150PIN_NULL = 10155,
        ANCHORAPUELLAE_BONE_HIPS_LEFT_Y90PIN_NULL = 10156,
        ANCHORAPUELLAE_NAVMESHAGENT_NULL = 10157,

        ANCHORAPUELLAE_CRINIS_PREFAB_INSTANCE_NULL = 10160,
        ANCHORAPUELLAE_CRINIS_RADIX_NULL = 10161,
        ANCHORAPUELLAE_CRINIS_INSTANCE_NULL = 10162,
        ANCHORAPUELLAE_CRINIS_INFERIOR_ANCHOR_NULL = 10163,

        ANCHORAPUNCTUMVIAE_CONSEQUENS_NULL = 10170,
        ANCHORAPUNCTUMVIAE_CONSEQUENS_LENGTH_OF_P_CONSEQUENS_IS_GREATER_THAN_21 = 10171,

        ANCHORACIVIS_INSTANTIATE_FAILED = 10172,
        ANCHORAPUELLAE_CRINIS_INSTANTIATE_FAILED = 10173,

        ANCHORAPUELLAE_BONE_VISAE_CAPITIS_NULL = 10174,
        ANCHORAPUELLAE_BONE_VISAE_PECTORIS_NULL = 10175,
        ANCHORAPUELLAE_BONE_VISAE_NATIUM_NULL = 10176,

        ANCHORACIVIS_CAPITIS_NULL = 10177,
        ANCHORAPUELLAE_BONE_NUDUS_PECTORIS_NULL = 10178,
        ANCHORAPUELLAE_BONE_NUDUS_CATELLUS_NULL = 10179,
        ANCHORAPUELLAE_BONE_NUDUS_NATIUM_NULL = 10180,

        // MinisteriaUnity.ConfiguratioDucis: 11000 ~

        // MinisteriaUnity.ConfiguratioMinisterii: 12000 ~

        // MinisteriaUnity.ContractusMinisterii: 13000 ~

        // MinisteriaUnity.MinisteriaRationis: 15000 ~
        LUDITORANIMATIONIS_FOUND_BLOCKING_AND_LOOPING = 15000,

        MINISTERIUMCIVIS_CONFIGURATION_NULL = 15010,
        MINISTERIUMCIVIS_CIVIS_PREFAB_NULL = 15011,
        MINISTERIUMCIVIS_ANIMATOR_NULL = 15012,
        MINISTERIUMCIVIS_HEAD_BONE_NULL = 15013,
        MINISTERIUMCIVIS_ACTIVATENPC_FAILED = 15014,
        MINISTERIUMCIVIS_NO_CIVIS_COMPONENT_IN_CIVISROOT = 15015,
        MINISTERIUMCIVIS_CHARACTERCONTROLLER_NULL = 15016,

        CIVIS_INSTANTIATE_FAILED = 15020,
        CIVIS_WAYPOINT_LOST = 15021,
        TABULAPUNCTUMVIAE_GAMEOBJECT_HAS_NO_ANCHORA = 15022,

        CIVISLOCI_INCIPEREMIGRARE_TO_NO_INSTANCE = 15023,
        CIVISLOCI_MIGRARE_TO_NO_INSTANCE = 15024,
        CIVISLOCI_MIGRARE_NOT_AT_DESTINATION = 15025,
        CIVISLOCI_MIGRARE_NOT_IN_MIGRATION = 15026,
        LUDITORPUNCTUMVIAE_NO_CREMATORIUM_OR_NATORIUM = 15027,

        PUNCTUMVIAE_RESOLVOR_NULL = 15040,
        PUNCTUMVIAE_LENGTH_OF_P_CONSEQUENS_IS_ZERO = 15041,
        PUNCTUMVIAE_ACTIVE_WAYPOINT_NOT_FOUND = 15042,
        PUNCTUMVIAE_LENGTH_OF_P_CONSEQUENS_IS_GREATER_THAN_21 = 15043,
        PUNCTUMVIAE_MONOBEHAVIOUR_ITEM_IS_NULL = 15044,
        PUNCTUMVIAE_MONOBEHAVIOUR_ITEM_IS_NOT_IPUNCTUMVIAE = 15045,
        PUNCTUMVIAE_MONOBEHAVIOURS_NULL_OR_EMPTY = 15046,
        PUNCTUMVIAE_RESOLVOR_CREATION_FAILED = 15047,
        PUNCTUMVIAE_ANCHOR_NULL = 15048,
        PUNCTUMVIAE_IACEREORDINEM_DIFFERENT_LENGTH = 15049,


        MINISTERIUMPUELLAERELATIONISTERRAE_RIGHT_FOOT_NULL = 15050,
        MINISTERIUMPUELLAERELATIONISTERRAE_LEFT_FOOT_NULL = 15051,
        MINISTERIUMPUELLAERELATIONISTERRAE_RIGHT_TOE_NULL = 15052,
        MINISTERIUMPUELLAERELATIONISTERRAE_LEFT_TOE_NULL = 15053,
        MINISTERIUMPUELLAERELATIONISTERRAE_RAYCAST_STRATUM_NULL = 15054,

        MINISTERIUMPUELLAEFIGURAEPELVIS_MESH_NULL = 15060,
        TABULAPUELLAEFIGURAEPELVIS_MESH_NULL = 15061,
        TABULAPUELLAEFIGURAEGENUS_MESH_NULL = 15062,
        MINISTERIUMPUELLAEFIGURAEGENUS_MESH_NULL = 15063,

        MINISTERIUMPUELLAEANIMATIONES_ANIMANCER_NULL = 15070,
        TABULAPUELLAEANIMATIONUMCORPORIS_ANIMATION_NULL = 15071,
        TABULAPUELLAEANIMATIONUMFUNDAMENTI_ANIMATION_NULL = 15072,
        TABULAPUELLAEANIMATIONUMPARTIS_ANIMATION_NULL = 15073,
        TABULAPUELLAEANIMATIONUMCORPORIS_CONFIG_NOT_FOUND = 15074,
        TABULAPUELLAEANIMATIONUMFUNDAMENTI_CONFIG_NOT_FOUND = 15075,
        TABULAPUELLAEANIMATIONUMPARTIS_CONFIG_NOT_FOUND = 15076,
        TABULAPUELLAEANIMATIONUMCONTINUATA_CONFIG_NOT_FOUND = 15077,

        MINIATERIUMPUELLAELOCI_CHARACTERCONTROLLER_NULL = 15080,

        TABULAPUELLAEOSSIUM_RIG_ROOT_NULL = 15090,

        TABULAPUELLAECRINIS_RESILIENS_CRINIS_NULL = 15100,

        MINISTERIUMCAMERA_CAMERA_NULL = 15110,

        MINISTERIUMINPUTMOTUS_MOVE_INPUT_NULL = 15120,
        MINISTERIUMINPUTMOTUS_SPRINT_INPUT_NULL = 15121,
        MINISTERIUMINPUTMOTUS_CROUCH_INPUT_NULL = 15122,

        OSTIUMPUELLAERELATIONISTERRAELEGIBILE_INSTANCE_NULL = 15123,
        MINISTERIUMPUELLAERELATIONISTERRAE_CONFIG_NULL = 15124,

        OSTIUMPUELLAEFIGURAEPELVISLEGIBILE_INSTANCE_NULL = 15125,
        OSTIUMPUELLAEFIGURAEPELVISMUTABILE_INSTANCE_NULL = 15126,
        TABULAPUELLAEFIGURAEPELVIS_BLEND_SHAPE_NOT_FOUND = 15127,
        TABULAPUELLAEFIGURAEGENUS_BLEND_SHAPE_NOT_FOUND = 15128,
        OSTIUMPUELLAEFIGURAEGENUSMUTABILE_INSTANCE_NULL = 15129,
        OSTIUMPUELLAEFIGURAEGENUSLEGIBILE_INSTANCE_NULL = 15130,

        MINISTERIUMPUELLAEANIMATIONES_CONFIG_NULL = 15131,
        TABULAPUELLAEANIMATIONUMCORPORIS_ANIMATION_NOT_FOUND = 15132,
        TABULAPUELLAEANIMATIONUMFUNDAMENTI_PLAN_NOT_FOUND = 15133,
        OSTIUMPUELLAEANIMATIONESMUTABILE_INSTANCE_NULL = 15134,

        OSTIUMPUELLAELOCIMUTABILE_INSTANCE_NULL = 15135,
        OSTIUMPUELLAELOCILEGIBILE_INSTANCE_NULL = 15136,
        OSTIUMPUELLAELOCINAVMESHMUTABILE_INSTANCE_NULL = 15137,
        OSTIUMPUELLAELOCINAVMESHLEGIBILE_INSTANCE_NULL = 15138,
        MINIATERIUMPUELLAELOCI_CONFIG_NULL = 15139,
        MINIATERIUMPUELLAELOCI_TEMPORIS_NULL = 15140,

        FASCICULUSOSTIORUMPUELLAE_CONFIG_NULL = 15141,

        OSSTIUMPUELLAEOSSISMUTABILE_INSTANCE_NULL = 15142,
        TABULAPUELLAEOSSIUM_BONE_NOT_FOUND = 15143,
        MINISTERIUMPUELLAEOSSIS_CONFIG_NULL = 15144,
        OSTIUMPUELLAEOSSISLEGIBILE_INSTANCE_NULL = 15145,

        MINISTERIUMPUELLAECRINISADIUNCTIONIS_CONFIG_NULL = 15146,
        OSTIUMPUELLAECRINISADIUNCTIONISMUTABILE_INSTANCE_NULL = 15147,
        TABULAPUELLAECRINIS_ID_NOT_FOUND = 15148,
        CRINISPUELLAE_CRINIS_NULL = 15149,
        CRINISPUELLAE_INSTANCE_NOT_FOUND = 15150,
        CRINISPUELLAE_RADIX_NOT_FOUND = 15151,

        FASCICULUSOSTIORUMCAMERA_CONFIG_NULL = 15152,
        OSTIUMCAMERAMUTABILE_INSTANCE_NULL = 15153,
        OSTIUMCAMERALEGIBILE_INSTANCE_NULL = 15154,

        LUDITORANIMATIONIS_LAYER_NOT_FOUND = 15155,
        TEMPORIS_INSTANCE_NULL = 15156,

        OSTIUMINPUTMOTUSLEGIBILE_INSTANCE_NULL = 15157,
        FASCICULUSOSTIORUMINPUT_CONFIG_NULL = 15158,

        MINISTERIA_CONFIGURATION_NULL = 15159,
        OSTIUMTEMPORISLEGIBILE_TEMPORIS_NULL = 15160,


        MINISTERIUMPUNCTUMVIAE_CONFIGURATION_NULL = 15162,

        MINISTERIUMPUELLAECRINISADIUNCTIONIS_INSTANTIATE_FAILED = 15163,

        CONFIGURATIOPUELLAEANIMATIONISCONTINUATA_CHILDREN_NULL_OR_EMPTY = 15164,

        MINISTERIUMPUNCTUMVIAE_NO_ACTIVE_ADITRIUM = 15165,
        MINISTERIUMPUNCTUMVIAE_NO_ACTIVE_CREMATORIUM = 15166,
        MINISTERIUMPUNCTUMVIAE_NO_ACTIVE_NATORIUM = 15167,
        MINISTERIUMPUNCTUMVIAE_NO_ACTIVE_POINT = 15168,

        TABULACIVISANIMATIONUMCONTINUATA_CONFIG_NOT_FOUND = 15169,
        CONFIGURATIOCIVISANIMATIONISCONTINUATA_CHILDREN_NULL_OR_EMPTY = 15170,

        OSTIUMCIVIUMLEGIBILE_OSTIUM_NULL = 15170,
        OSTIUMCIVIUMMUTABILE_OSTIUM_NULL = 15171,

        TABULACIVIS_ANCHORAE_NULL = 15172,
        TABULACIVIS_ANCHORA_NULL = 15173,
        TABULACIVIS_ANCHORA_DUPLICATE = 15174,

        MINISTERIUMCIVISANIMATIONES_CONSTUCT_BEFORE_ANCHORA_INITIALIZATION = 15175,
        GENERATORCIVIS_TIMEOUT_INITIARE = 15176,

        MINISTERIUMPUELLAE_UNINITIALIZED_RESVISAE_CAPITIS = 15177,
        MINISTERIUMPUELLAE_UNINITIALIZED_RESVISAE_PECTORIS = 15178,
        MINISTERIUMPUELLAE_UNINITIALIZED_RESVISAE_NATIUM = 15179,

        CIVIS_ADINCARNARE_ALREADY_SET = 15180,
        CIVIS_ADSPIRITUARE_ALREADY_SET = 15181,

        MINISTERIUMPUELLAE_UNINITIALIZED_RESNUDUS_ANTERIOR = 15182,
        MINISTERIUMPUELLAE_UNINITIALIZED_RESNUDUS_POSTERIOR = 15183,

        // Dux.ContractusDucis: 21000 ~
        // Dux.Thesaurus: 22000 ~
        // Dux.Miles: 25000 ~
        TABULASTATUUMCORPORIS_STATUS_MISSING = 25000,
        TABULASTATUUMCORPORIS_STATUS_MISMATCH = 25001,
        TABULASTATUUMCORPORIS_CONFIGURATIO_MISSING = 25002,
        TABULASTATUUMPARTIS_CONFIGURATIO_MISSING = 25003,
        FABRICAPUELLAEORDDINATORMODI_MODUS_NOT_FOUND = 25004,
        FABRICACIVISMODINAVMESH_MODI_NOT_FOUND = 25005,

        NPC_INITIALIZATION_FAILED_NO_WAYPOINT = 25006,
        NPC_GENERATION_FAILED_NO_WAYPOINT = 25007,
        ORDINATIOPUELLAEACTIONIS_GET_MISSMATCH_SPECIES = 25008,
        ORDINATIOPUELLAEACTIONIS_INVALID_SPECIES = 25009,
        FABRICAPUELLAESTATUSCORPORIS_MODUS_NOT_FOUND = 25010,
        MACHINAPUELLAESTATUUMCORPORIS_STATUS_MISSING = 25011,
        FABRICAPUELLAESTATUSCORPORIS_INVALID_CONFIGURATION = 25012,
        ORDINATIOCIVISACTIONIS_GET_MISSMATCH_SPECIES = 25013,
        ORDINATIOCIVISACTIONIS_INVALID_SPECIES = 25014,

        FABRICACIVISSTATUSCORPORIS_MODUS_NOT_FOUND = 25015,
        FABRICACIVISSTATUSCORPORIS_INVALID_CONFIGURATION = 25016,
        MACHINACIVISSTATUUMCORPORIS_STATUS_MISSING = 25017,
        ORDINATIOCIVISVELETUDINISCUSTODIAE_INVALID_SPECIES = 25018,
        MILIESCIVISCUSTODIAE_CONARELEGO_FAILED = 25019,

        MINIATERIUMPUELLAELOCI_EXECUTARE_CALLED_MORE_THAN_ONCE = 25020, 
        MINIATERIUMPUELLAELOCI_APPLICARE_MOTUS_NULL = 25021,
        MINIATERIUMPUELLAELOCI_APPLICARE_NAVMESH_NULL = 25022,

        MINIATERIUMPUELLAEFIGURA_GENUS_ORDINATIO_QUEUE_FULL = 25023,
        MINIATERIUMPUELLAEFIGURA_PELVIS_ORDINATIO_QUEUE_FULL = 25024,

        MINIATERIUMPUELLAECRINIS_ORDINATIO_QUEUE_FULL = 25025,
        MINIATERIUMPUELLAEANIMATION_ORDINATIO_QUEUE_FULL = 25026,

        // LacusOrdinatioPuellae: 25027 ~
        ORDINATIOPUELLAEANIMATIONIS_EMISSIO_QUEUE_FULL = 25027,
        ORDINATIOPUELLAEANIMATIONIS_LACUS_EMPTY = 25028,
        ORDINATIOPUELLAECRINIS_EMISSIO_QUEUE_FULL = 25029,
        ORDINATIOPUELLAECRINIS_LACUS_EMPTY = 25030,
        ORDINATIOPUELLAEFIGURAEGENUS_EMISSIO_QUEUE_FULL = 25031,
        ORDINATIOPUELLAEFIGURAEGENUS_LACUS_EMPTY = 25032,
        ORDINATIOPUELLAEFIGURAEPELVIS_EMISSIO_QUEUE_FULL = 25033,
        ORDINATIOPUELLAEFIGURAEPELVIS_LACUS_EMPTY = 25034,
        ORDINATIOPUELLAEMOTUS_EMISSIO_QUEUE_FULL = 25035,
        ORDINATIOPUELLAEMOTUS_LACUS_EMPTY = 25036,
        ORDINATIOPUELLAENAVMESH_EMISSIO_QUEUE_FULL = 25037,
        ORDINATIOPUELLAENAVMESH_LACUS_EMPTY = 25038,
        ORDINATIOPUELLAEVELETUDINIS_EMISSIO_QUEUE_FULL = 25039,
        ORDINATIOPUELLAEVELETUDINIS_LACUS_EMPTY = 25040,
        ORDINATIOPUELLAEANIMATIONIS_LACUS_FULL = 25041,
        ORDINATIOPUELLAECRINIS_LACUS_FULL = 25042,
        ORDINATIOPUELLAEFIGURAEGENUS_LACUS_FULL = 25043,
        ORDINATIOPUELLAEFIGURAEPELVIS_LACUS_FULL = 25044,
        ORDINATIOPUELLAEMOTUS_LACUS_FULL = 25045,
        ORDINATIOPUELLAENAVMESH_LACUS_FULL = 25046,
        ORDINATIOPUELLAEVELETUDINIS_LACUS_FULL = 25047,

        EXECUTORCIVISLOCI_ORDINATIO_MOTUS_QUEUE_FULL = 25048,
        EXECUTORCIVISLOCI_ORDINATIO_NAVMESH_QUEUE_FULL = 25049,
        EXECUTORCIVISLOCI_APPLICARE_MOTUS_NULL = 25050,
        EXECUTORCIVISLOCI_APPLICARE_NAVMESH_NULL = 25051,

        EXECUTORPUELLAELOCI_ORDINATIO_MOTUS_QUEUE_FULL = 25052,
        EXECUTORPUELLAELOCI_ORDINATIO_NAVMESH_QUEUE_FULL = 25053,
        EXECUTORPUELLAELOCI_APPLICARE_MOTUS_NULL = 25054,
        EXECUTORPUELLAELOCI_APPLICARE_NAVMESH_NULL = 25055,
        EXECUTORCIVISLOCI_INITARE_TRANSPORTO_FAILED = 25057,
        EXECUTORCIVISLOCI_PURGARE_TRANSPORTO_FAILED = 25058,
        EXECUTORCIVISANIMATIONIS_ORDINATIO_QUEUE_FULL = 25059,
        

        EXECUTORCIVISANIMATION_ORDINATIO_QUEUE_FULL = 25060,
        EXECUTORCIVISMORTIS_ORDINATIO_QUEUE_FULL = 25061,

        ORDINATIOPUELLAEVELETUDINISNUDI_EMISSIO_QUEUE_FULL = 25062,
        ORDINATIOPUELLAEVELETUDINISNUDI_LACUS_EMPTY = 25063,
        ORDINATIOPUELLAEVELETUDINISNUDI_LACUS_FULL = 25064,

        EXECUTORPUELLAEVELETUDINIS_ORDINATIO_VELETUDINISNUDI_QUEUE_FULL = 25065,

        MILIESCIVISCUSTODIAE_RESOLVERESPECTARENUDUS_FAILED = 25066,

        EXECUTORCIVISVELETUDINISVALORIS_ORDINATIO_QUEUE_FULL = 25067,
        EXECUTORCIVISVELETUDINISVALORIS_APPLICARE_SPECTARE_NULL = 25068,

        ABACUSDISTANTIAEVISUS_INVALID_DISTANTIA = 25069,
        ABACUSANGULIVISUS_INVALID_ANGULUS = 25070,

        RESOLUTORCIVISICTUUM_CONARELEGO_FAILED = 25071,

        RESOLUTORCIVISNUDUSVISAE_CONARELEGO_FAILED = 25072,

        TAIL = 1000000000
    }
}
