namespace Yulinti.Nucleus {
    public enum IDErrorum {
        OK = 0,

        // Rex: 1000 ~

        // Nucleus: 2000 ~

        // MinisteriaUnity.ConfiguratioDucis: 11000 ~

        // MinisteriaUnity.ConfiguratioMinisterii: 12000 ~

        // MinisteriaUnity.ContractusMinisterii: 13000 ~

        // MinisteriaUnity.MinisteriaRationis: 15000 ~
        LUDITORANIMATIONIS_FOUND_BLOCKING_AND_LOOPING = 15000,

        MINISTERIUMCIVIS_CONFIGURATION_NULL = 15010,
        MINISTERIUMCIVIS_CIVIS_PREFAB_NULL = 15011,
        MINISTERIUMCIVIS_ANIMATOR_NULL = 15012,
        MINISTERIUMCIVIS_HEAD_BONE_NULL = 15013,
        MINISTERIUMCIVIS_ACTIVATENPC_FAILED = 15014,
        MINISTERIUMCIVIS_NO_CIVIS_COMPONENT_IN_CIVISROOT = 15015,
        MINISTERIUMCIVIS_CHARACTERCONTROLLER_NULL = 15016,

        CIVISATOMI_INSTANTIATE_FAILED = 15020,
        CIVISATOMI_ANIMATOR_NULL = 15021,
        CIVISATOMI_NO_ANCHOR_IN_ROOT = 15022,

        PUNCTUMVIAE_RESOLVOR_NULL = 15040,
        PUNCTUMVIAE_LENGTH_OF_P_CONSEQUENS_IS_ZERO = 15041,
        PUNCTUMVIAE_ACTIVE_WAYPOINT_NOT_FOUND = 15042,
        PUNCTUMVIAE_LENGTH_OF_P_CONSEQUENS_IS_GREATER_THAN_21 = 15043,
        PUNCTUMVIAE_MONOBEHAVIOUR_ITEM_IS_NULL = 15044,
        PUNCTUMVIAE_MONOBEHAVIOUR_ITEM_IS_NOT_IPUNCTUMVIAE = 15045,
        PUNCTUMVIAE_MONOBEHAVIOURS_NULL_OR_EMPTY = 15046,
        PUNCTUMVIAE_RESOLVOR_CREATION_FAILED = 15047,
        PUNCTUMVIAE_ANCHOR_NULL = 15048,


        MINISTERIUMPUELLAERELATIONISTERRAE_RIGHT_FOOT_NULL = 15050,
        MINISTERIUMPUELLAERELATIONISTERRAE_LEFT_FOOT_NULL = 15051,
        MINISTERIUMPUELLAERELATIONISTERRAE_RIGHT_TOE_NULL = 15052,
        MINISTERIUMPUELLAERELATIONISTERRAE_LEFT_TOE_NULL = 15053,
        MINISTERIUMPUELLAERELATIONISTERRAE_RAYCAST_STRATUM_NULL = 15054,

        MINISTERIUMPUELLAEFIGURAEPELVIS_MESH_NULL = 15060,
        TABULAPUELLAEFIGURAEPELVIS_MESH_NULL = 15061,
        TABULAPUELLAEFIGURAEGENUS_MESH_NULL = 15062,
        MINISTERIUMPUELLAEFIGURAEGENUS_MESH_NULL = 15063,

        MINISTERIUMPUELLAEANIMATIONES_ANIMANCER_NULL = 15070,
        TABULAPUELLAEANIMATIONUMCORPORIS_CROUCH_NULL = 15071,
        TABULAPUELLAEANIMATIONUMFUNDAMENTI_STANDARD_BASE_NULL = 15072,

        MINIATERIUMPUELLAELOCI_CHARACTERCONTROLLER_NULL = 15080,

        TABULAPUELLAEOSSIUM_RIG_ROOT_NULL = 15090,

        TABULAPUELLAECRINIS_RESILIENS_CRINIS_NULL = 15100,

        MINISTERIUMCAMERA_CAMERA_NULL = 15110,

        MINISTERIUMINPUTMOTUS_MOVE_INPUT_NULL = 15120,
        MINISTERIUMINPUTMOTUS_SPRINT_INPUT_NULL = 15121,
        MINISTERIUMINPUTMOTUS_CROUCH_INPUT_NULL = 15122,

        OSTIUMPUELLAERELATIONISTERRAELEGIBILE_INSTANCE_NULL = 15123,
        MINISTERIUMPUELLAERELATIONISTERRAE_CONFIG_NULL = 15124,

        OSTIUMPUELLAEFIGURAEPELVISLEGIBILE_INSTANCE_NULL = 15125,
        OSTIUMPUELLAEFIGURAEPELVISMUTABILE_INSTANCE_NULL = 15126,
        TABULAPUELLAEFIGURAEPELVIS_BLEND_SHAPE_NOT_FOUND = 15127,
        TABULAPUELLAEFIGURAEGENUS_BLEND_SHAPE_NOT_FOUND = 15128,
        OSTIUMPUELLAEFIGURAEGENUSMUTABILE_INSTANCE_NULL = 15129,
        OSTIUMPUELLAEFIGURAEGENUSLEGIBILE_INSTANCE_NULL = 15130,

        MINISTERIUMPUELLAEANIMATIONES_CONFIG_NULL = 15131,
        TABULAPUELLAEANIMATIONUMCORPORIS_ANIMATION_NOT_FOUND = 15132,
        TABULAPUELLAEANIMATIONUMFUNDAMENTI_PLAN_NOT_FOUND = 15133,
        OSTIUMPUELLAEANIMATIONESMUTABILE_INSTANCE_NULL = 15134,

        OSTIUMPUELLAELOCIMUTABILE_INSTANCE_NULL = 15135,
        OSTIUMPUELLAELOCILEGIBILE_INSTANCE_NULL = 15136,
        MINIATERIUMPUELLAELOCI_CONFIG_NULL = 15137,
        MINIATERIUMPUELLAELOCI_TEMPORIS_NULL = 15138,

        FASCICULUSOSTIORUMPUELLAE_CONFIG_NULL = 15139,

        OSSTIUMPUELLAEOSSISMUTABILE_INSTANCE_NULL = 15140,
        TABULAPUELLAEOSSIUM_BONE_NOT_FOUND = 15141,
        MINISTERIUMPUELLAEOSSIS_CONFIG_NULL = 15142,
        OSTIUMPUELLAEOSSISLEGIBILE_INSTANCE_NULL = 15143,

        MINISTERIUMPUELLAECRINISADIUNCTIONIS_CONFIG_NULL = 15144,
        OSTIUMPUELLAECRINISADIUNCTIONISMUTABILE_INSTANCE_NULL = 15145,
        TABULAPUELLAECRINIS_ID_NOT_FOUND = 15146,
        CRINISPUELLAE_CRINIS_NULL = 15147,
        CRINISPUELLAE_INSTANCE_NOT_FOUND = 15148,
        CRINISPUELLAE_RADIX_NOT_FOUND = 15149,

        FASCICULUSOSTIORUMCAMERA_CONFIG_NULL = 15150,
        OSTIUMCAMERAMUTABILE_INSTANCE_NULL = 15151,
        OSTIUMCAMERALEGIBILE_INSTANCE_NULL = 15152,

        LUDITORANIMATIONIS_LAYER_NOT_FOUND = 15153,
        TEMPORIS_INSTANCE_NULL = 15154,

        OSTIUMINPUTMOTUSLEGIBILE_INSTANCE_NULL = 15155,
        FASCICULUSOSTIORUMINPUT_CONFIG_NULL = 15156,

        MINISTERIA_CONFIGURATION_NULL = 15157,
        OSTIUMTEMPORISLEGIBILE_TEMPORIS_NULL = 15158,


        MINISTERIUMPUNCTUMVIAE_CONFIGURATION_NULL = 15160,

        // Dux.ContractusDucis: 21000 ~
        // Dux.Thesaurus: 22000 ~
        // Dux.Miles: 25000 ~
        TABULASTATUUMCORPORIS_STATUS_MISSING = 25000,
        TABULASTATUUMCORPORIS_STATUS_MISMATCH = 25001,

        TAIL = 1000000000
    }
}
