namespace Yulinti.Nucleus {
    public enum IDErrorum {
        OK = 0,

        // Rex: 1000 ~
        REX_ANCHORA_NOT_SET = 1000,
        REX_ANCHORA_RESOLVE_FAILED = 1001,

        // Nucleus: 2000 ~

        // MinisteriaUnity.Anchora: 10000~
        ANCHORACAMERA_CAMERA_NULL = 10000,

        ANCHORACIVIS_PREFAB_INSTANCE_NULL = 10010,
        ANCHORACIVIS_ANIMATOR_NULL = 10011,
        ANCHORACIVIS_SKINNEDMESHRENDERER_NULL = 10012,
        ANCHORACIVIS_CHARACTERCONTROLLER_NULL = 10013,
        ANCHORACIVIS_NAVMESHAGENT_NULL = 10014,
        ANCHORACIVIS_INSTANCE_NULL = 10015,
        ANCHORACIVIS_INFERIOR_ANCHOR_NULL = 10016,
        
        ANCHORAINPUT_MOVEINPUT_NULL = 10020,
        ANCHORAINPUT_SPRINTINPUT_NULL = 10021,
        ANCHORAINPUT_CROUCHINPUT_NULL = 10022,

        ANCHORAPUELLAE_CHARACTERCONTROLLER_NULL = 10100,
        ANCHORAPUELLAE_ANIMATOR_NULL = 10102,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_HEAD_NULL = 10110,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_PELVIS_NULL = 10111,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_TORSO_NULL = 10112,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_RIGHTARM_NULL = 10113,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_LEFTARM_NULL = 10114,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_RIGHTLEG_NULL = 10115,
        ANCHORAPUELLAE_SKINNEDMESHRENDERER_LEFTLEG_NULL = 10116,
        ANCHORAPUELLAE_BONE_ROOT_NULL = 10130,
        ANCHORAPUELLAE_BONE_HIPS_NULL = 10131,
        ANCHORAPUELLAE_BONE_SPINE_NULL = 10132,
        ANCHORAPUELLAE_BONE_SPINE1_NULL = 10133,
        ANCHORAPUELLAE_BONE_SPINE2_NULL = 10134,
        ANCHORAPUELLAE_BONE_NECK_NULL = 10135,
        ANCHORAPUELLAE_BONE_HEAD_NULL = 10136,
        ANCHORAPUELLAE_BONE_LEFTSHOULDER_NULL = 10137,
        ANCHORAPUELLAE_BONE_LEFTUPPERARM_NULL = 10138,
        ANCHORAPUELLAE_BONE_LEFTLOWERARM_NULL = 10139,
        ANCHORAPUELLAE_BONE_LEFTHAND_NULL = 10140,
        ANCHORAPUELLAE_BONE_RIGHTSHOULDER_NULL = 10141,
        ANCHORAPUELLAE_BONE_RIGHTUPPERARM_NULL = 10142,
        ANCHORAPUELLAE_BONE_RIGHTLOWERARM_NULL = 10143,
        ANCHORAPUELLAE_BONE_RIGHTHAND_NULL = 10144,
        ANCHORAPUELLAE_BONE_LEFTUPPERLEG_NULL = 10145,
        ANCHORAPUELLAE_BONE_LEFTLOWERLEG_NULL = 10146,
        ANCHORAPUELLAE_BONE_LEFTFOOT_NULL = 10147,
        ANCHORAPUELLAE_BONE_LEFTTOE_NULL = 10148,
        ANCHORAPUELLAE_BONE_RIGHTUPPERLEG_NULL = 10149,
        ANCHORAPUELLAE_BONE_RIGHTLOWERLEG_NULL = 10150,
        ANCHORAPUELLAE_BONE_RIGHTFOOT_NULL = 10151,
        ANCHORAPUELLAE_BONE_RIGHTTOE_NULL = 10152,
        ANCHORAPUELLAE_BONE_HIPS_RIGHT_X150PIN_NULL = 10153,
        ANCHORAPUELLAE_BONE_HIPS_RIGHT_Y90PIN_NULL = 10154,
        ANCHORAPUELLAE_BONE_HIPS_LEFT_X150PIN_NULL = 10155,
        ANCHORAPUELLAE_BONE_HIPS_LEFT_Y90PIN_NULL = 10156,

        ANCHORAPUELLAE_CRINIS_PREFAB_INSTANCE_NULL = 10160,
        ANCHORAPUELLAE_CRINIS_RADIX_NULL = 10161,
        ANCHORAPUELLAE_CRINIS_INSTANCE_NULL = 10162,
        ANCHORAPUELLAE_CRINIS_INFERIOR_ANCHOR_NULL = 10163,

        ANCHORAPUNCTUMVIAE_CONSEQUENS_NULL = 10170,
        ANCHORAPUNCTUMVIAE_CONSEQUENS_LENGTH_OF_P_CONSEQUENS_IS_GREATER_THAN_21 = 10171,

        // MinisteriaUnity.ConfiguratioDucis: 11000 ~

        // MinisteriaUnity.ConfiguratioMinisterii: 12000 ~

        // MinisteriaUnity.ContractusMinisterii: 13000 ~

        // MinisteriaUnity.MinisteriaRationis: 15000 ~
        LUDITORANIMATIONIS_FOUND_BLOCKING_AND_LOOPING = 15000,

        MINISTERIUMCIVIS_CONFIGURATION_NULL = 15010,
        MINISTERIUMCIVIS_CIVIS_PREFAB_NULL = 15011,
        MINISTERIUMCIVIS_ANIMATOR_NULL = 15012,
        MINISTERIUMCIVIS_HEAD_BONE_NULL = 15013,
        MINISTERIUMCIVIS_ACTIVATENPC_FAILED = 15014,
        MINISTERIUMCIVIS_NO_CIVIS_COMPONENT_IN_CIVISROOT = 15015,
        MINISTERIUMCIVIS_CHARACTERCONTROLLER_NULL = 15016,

        CIVIS_INSTANTIATE_FAILED = 15020,
        CIVIS_WAYPOINT_LOST = 15021,
        TABULAPUNCTUMVIAE_GAMEOBJECT_HAS_NO_ANCHORA = 15022,

        PUNCTUMVIAE_RESOLVOR_NULL = 15040,
        PUNCTUMVIAE_LENGTH_OF_P_CONSEQUENS_IS_ZERO = 15041,
        PUNCTUMVIAE_ACTIVE_WAYPOINT_NOT_FOUND = 15042,
        PUNCTUMVIAE_LENGTH_OF_P_CONSEQUENS_IS_GREATER_THAN_21 = 15043,
        PUNCTUMVIAE_MONOBEHAVIOUR_ITEM_IS_NULL = 15044,
        PUNCTUMVIAE_MONOBEHAVIOUR_ITEM_IS_NOT_IPUNCTUMVIAE = 15045,
        PUNCTUMVIAE_MONOBEHAVIOURS_NULL_OR_EMPTY = 15046,
        PUNCTUMVIAE_RESOLVOR_CREATION_FAILED = 15047,
        PUNCTUMVIAE_ANCHOR_NULL = 15048,
        PUNCTUMVIAE_IACEREORDINEM_DIFFERENT_LENGTH = 15049,


        MINISTERIUMPUELLAERELATIONISTERRAE_RIGHT_FOOT_NULL = 15050,
        MINISTERIUMPUELLAERELATIONISTERRAE_LEFT_FOOT_NULL = 15051,
        MINISTERIUMPUELLAERELATIONISTERRAE_RIGHT_TOE_NULL = 15052,
        MINISTERIUMPUELLAERELATIONISTERRAE_LEFT_TOE_NULL = 15053,
        MINISTERIUMPUELLAERELATIONISTERRAE_RAYCAST_STRATUM_NULL = 15054,

        MINISTERIUMPUELLAEFIGURAEPELVIS_MESH_NULL = 15060,
        TABULAPUELLAEFIGURAEPELVIS_MESH_NULL = 15061,
        TABULAPUELLAEFIGURAEGENUS_MESH_NULL = 15062,
        MINISTERIUMPUELLAEFIGURAEGENUS_MESH_NULL = 15063,

        MINISTERIUMPUELLAEANIMATIONES_ANIMANCER_NULL = 15070,
        TABULAPUELLAEANIMATIONUMCORPORIS_CROUCH_NULL = 15071,
        TABULAPUELLAEANIMATIONUMFUNDAMENTI_STANDARD_BASE_NULL = 15072,

        MINIATERIUMPUELLAELOCI_CHARACTERCONTROLLER_NULL = 15080,

        TABULAPUELLAEOSSIUM_RIG_ROOT_NULL = 15090,

        TABULAPUELLAECRINIS_RESILIENS_CRINIS_NULL = 15100,

        MINISTERIUMCAMERA_CAMERA_NULL = 15110,

        MINISTERIUMINPUTMOTUS_MOVE_INPUT_NULL = 15120,
        MINISTERIUMINPUTMOTUS_SPRINT_INPUT_NULL = 15121,
        MINISTERIUMINPUTMOTUS_CROUCH_INPUT_NULL = 15122,

        OSTIUMPUELLAERELATIONISTERRAELEGIBILE_INSTANCE_NULL = 15123,
        MINISTERIUMPUELLAERELATIONISTERRAE_CONFIG_NULL = 15124,

        OSTIUMPUELLAEFIGURAEPELVISLEGIBILE_INSTANCE_NULL = 15125,
        OSTIUMPUELLAEFIGURAEPELVISMUTABILE_INSTANCE_NULL = 15126,
        TABULAPUELLAEFIGURAEPELVIS_BLEND_SHAPE_NOT_FOUND = 15127,
        TABULAPUELLAEFIGURAEGENUS_BLEND_SHAPE_NOT_FOUND = 15128,
        OSTIUMPUELLAEFIGURAEGENUSMUTABILE_INSTANCE_NULL = 15129,
        OSTIUMPUELLAEFIGURAEGENUSLEGIBILE_INSTANCE_NULL = 15130,

        MINISTERIUMPUELLAEANIMATIONES_CONFIG_NULL = 15131,
        TABULAPUELLAEANIMATIONUMCORPORIS_ANIMATION_NOT_FOUND = 15132,
        TABULAPUELLAEANIMATIONUMFUNDAMENTI_PLAN_NOT_FOUND = 15133,
        OSTIUMPUELLAEANIMATIONESMUTABILE_INSTANCE_NULL = 15134,

        OSTIUMPUELLAELOCIMUTABILE_INSTANCE_NULL = 15135,
        OSTIUMPUELLAELOCILEGIBILE_INSTANCE_NULL = 15136,
        MINIATERIUMPUELLAELOCI_CONFIG_NULL = 15137,
        MINIATERIUMPUELLAELOCI_TEMPORIS_NULL = 15138,

        FASCICULUSOSTIORUMPUELLAE_CONFIG_NULL = 15139,

        OSSTIUMPUELLAEOSSISMUTABILE_INSTANCE_NULL = 15140,
        TABULAPUELLAEOSSIUM_BONE_NOT_FOUND = 15141,
        MINISTERIUMPUELLAEOSSIS_CONFIG_NULL = 15142,
        OSTIUMPUELLAEOSSISLEGIBILE_INSTANCE_NULL = 15143,

        MINISTERIUMPUELLAECRINISADIUNCTIONIS_CONFIG_NULL = 15144,
        OSTIUMPUELLAECRINISADIUNCTIONISMUTABILE_INSTANCE_NULL = 15145,
        TABULAPUELLAECRINIS_ID_NOT_FOUND = 15146,
        CRINISPUELLAE_CRINIS_NULL = 15147,
        CRINISPUELLAE_INSTANCE_NOT_FOUND = 15148,
        CRINISPUELLAE_RADIX_NOT_FOUND = 15149,

        FASCICULUSOSTIORUMCAMERA_CONFIG_NULL = 15150,
        OSTIUMCAMERAMUTABILE_INSTANCE_NULL = 15151,
        OSTIUMCAMERALEGIBILE_INSTANCE_NULL = 15152,

        LUDITORANIMATIONIS_LAYER_NOT_FOUND = 15153,
        TEMPORIS_INSTANCE_NULL = 15154,

        OSTIUMINPUTMOTUSLEGIBILE_INSTANCE_NULL = 15155,
        FASCICULUSOSTIORUMINPUT_CONFIG_NULL = 15156,

        MINISTERIA_CONFIGURATION_NULL = 15157,
        OSTIUMTEMPORISLEGIBILE_TEMPORIS_NULL = 15158,


        MINISTERIUMPUNCTUMVIAE_CONFIGURATION_NULL = 15160,

        MINISTERIUMPUELLAECRINISADIUNCTIONIS_INSTANTIATE_FAILED = 15161,

        // Dux.ContractusDucis: 21000 ~
        // Dux.Thesaurus: 22000 ~
        // Dux.Miles: 25000 ~
        TABULASTATUUMCORPORIS_STATUS_MISSING = 25000,
        TABULASTATUUMCORPORIS_STATUS_MISMATCH = 25001,

        TAIL = 1000000000
    }
}
