namespace Yulinti.Exercitus.Contractus {
    public enum IDTextus {
        INDEXUS_PRINCIPALIS_LUDUS_NOVUS,
        INDEXUS_PRINCIPALIS_PERGE_LUDUM,
        INDEXUS_PRINCIPALIS_ONERA_LUDUM,
        INDEXUS_PRINCIPALIS_OPTIONES,
        INDEXUS_PRINCIPALIS_EXIT,

        SALSAMENTUM_HEADER_LABEL,
        SALSAMENTUM_LIST_MANUALIS_LABEL,
        SALSAMENTUM_LIST_AUTOMATICUS_LABEL,
        SALSAMENTUM_BUTTON_ONERA_LUDUM,
        SALSAMENTUM_BUTTON_DELETO_LUDUM,
        SALSAMENTUM_BUTTON_CANCEL,

        PUELLAEPERSONAE_GRADUS_LUXURIOSUS,
        PUELLAEPERSONAE_ANIMA_LUXURIOSUS,
        PUELLAEPERSONAE_GRADUS_EXHIBITUS,
        PUELLAEPERSONAE_ANIMA_EXHIBITUS,
        PUELLAEPERSONAE_GRADUS_PERVERSUS,
        PUELLAEPERSONAE_ANIMA_PERVERSUS,
        PUELLAEPERSONAE_GRADUS_QUAERIT_DOLOR,
        PUELLAEPERSONAE_ANIMA_QUAERIT_DOLOR,
        PUELLAEPERSONAE_SENSUS_PAPILLAE,
        PUELLAEPERSONAE_ANIMA_PAPILLAE,
        PUELLAEPERSONAE_SENSUS_LANDICAE,
        PUELLAEPERSONAE_ANIMA_LANDICAE,
        PUELLAEPERSONAE_SENSUS_VAGINAE,
        PUELLAEPERSONAE_ANIMA_VAGINAE,
        PUELLAEPERSONAE_SENSUS_ANI,
        PUELLAEPERSONAE_ANIMA_ANI,
        PUELLAEPERSONAE_SENSUS_AUSCULUM,
        PUELLAEPERSONAE_ANIMA_AUSCULUM,
        PUELLAEPERSONAE_SENSUS_CORPORIS,
        PUELLAEPERSONAE_ANIMA_CORPORIS 
    }
}